# @file nginx.conf
# @description Archivo de configuración para el servidor web Nginx.
# Este archivo define cómo Nginx debe manejar las solicitudes entrantes,
# sirviendo los archivos estáticos de la aplicación React y reescribiendo
# las URLs para permitir el enrutamiento del lado del cliente (client-side routing)
# sin recargar la página.
# @author Equipo 3
# @version 1.0.0

server {
  listen 80; # Nginx escuchará las conexiones entrantes en el puerto 80 (HTTP estándar).
  server_name localhost; # Define el nombre del servidor para el cual esta configuración es válida.

  root /usr/share/nginx/html; # Especifica el directorio raíz donde Nginx buscará los archivos estáticos de la aplicación.
  index index.html; # Define el archivo por defecto a servir cuando se accede a un directorio.

  location / {
    # Bloque de configuración para manejar todas las solicitudes.
    # try_files: Intenta servir el archivo solicitado ($uri), luego el directorio solicitado ($uri/),
    # y si ninguno existe, fallback a /index.html. Esto es fundamental para las SPA (Single Page Applications)
    # como React, permitiendo que el enrutador de la aplicación maneje las rutas.
    try_files $uri $uri/ /index.html;
  }
}